# Computer Vision - Assignment 2

## First Part - Spatial Filters

In [1]:
# Imports
import cv2
import matplotlib.pyplot as plt
import numpy as np
import urllib.request

from scipy.signal import correlate2d, convolve2d

# Misc.
def url2img(url):
  req = urllib.request.urlopen(url)
  arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
  return cv2.imdecode(arr, -1)

### Exercise 1 - Fundamentals

#### Exercise 1.1
During the lecture, you have become familiar with spatial correlation. As a reminder, the formula of the spatial correlation is as follows:

$$I'(x,y) = \sum_{s=-a}^a{\sum_{t=-b}^b} K(s,t) \times I(x+s, y+t) $$

where
- *K* is the Kernel of size $m\times n$, with $m=2a+1$ and $n=2b+1$ and $a,b > 0$
- $x$ and $y$ depict the pixels that are aligned with the center of the kernel
- *I* is the input image
- *I'* is the output


Implement this function in the following code cell without using any package or framework. For now, do not pad the input and assume that we have set ``stride=1``

In [116]:
def cross_correlation(input : np.ndarray, kernel : np.ndarray) -> np.ndarray:
  a = (kernel.shape[0]-1)/2
  b = (kernel.shape[1]-1)/2
  # Der output soll genau inputsize-kernelsize + 1 groß sein
  output = np.zeros((input.shape[0]-kernel.shape[0]+1, input.shape[1]-kernel.shape[1]+1))
  # Iteriere über jede column
  for idxLine, line in enumerate(input):
    #Spring raus, wenn man in der ersten oder letzten column ist (da kein padding angegeben wurde)
    if idxLine == 0 or idxLine == input.shape[0]-1: continue
    # Iteriere über jeden Wert der column
    for idxPixel, pixel in enumerate(line):
          #Spring raus, wenn man in dem ersten oder letzten Wert einer column ist (da kein padding angegeben wurde)
      if idxPixel == 0 or idxPixel == input.shape[1]-1: continue
      # Berechne für den jeweiligen Wert den Output Wert, indem die Umgebung mit dem Kernel multipliziert wird und die Werte aufsummiert werden
      for idxI, i in enumerate(np.arange(-a,a+1, dtype=int)):
        for idxJ, j in enumerate(np.arange(-b,b+1, dtype=int)):
          output[idxLine-1, idxPixel-1] += input[idxLine, idxPixel]*kernel[idxI, idxJ]
  return output


image = np.arange(100).reshape((20,5))
kernel = np.array([[1, 0, 1], [0, 1, 0], [1, 0, 1]])

output = cross_correlation(image, kernel)
print(output)

[[ 30.  35.  40.]
 [ 55.  60.  65.]
 [ 80.  85.  90.]
 [105. 110. 115.]
 [130. 135. 140.]
 [155. 160. 165.]
 [180. 185. 190.]
 [205. 210. 215.]
 [230. 235. 240.]
 [255. 260. 265.]
 [280. 285. 290.]
 [305. 310. 315.]
 [330. 335. 340.]
 [355. 360. 365.]
 [380. 385. 390.]
 [405. 410. 415.]
 [430. 435. 440.]
 [455. 460. 465.]]


In [99]:
image = np.arange(100).reshape((5,20))
kernel = np.array([[1,0,1],[0,1,0],[1,0,1]])

output = cross_correlation(image, kernel)
print(output)

[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]]
(5, 20)
[-1  0  1]
[-1  0  1]
3
18
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
pixel = 20
shape1 - 2 18
pixel = 21
shape1 - 2 18
idx: 1
idxPixel: 1
computedValueForOutput: 105
pixel = 22
shape1 - 2 18
idx: 1
idxPixel: 2
computedValueForOutput: 110
pixel = 23
shape1 - 2 18
idx: 1
idxPixel: 3
computedValueForOutput: 115
pixel = 24
shape1 - 2 18
idx: 1
idxPixel: 4
computedValueForOutput: 120
pixel = 25
shape1 - 2 18
idx: 1
idxPixel: 5
computedValueForOutput: 125
pixel = 26
shape1 - 2 18
idx: 1
idxPixel: 6
computedValueForOutput: 130
pixel = 27
shape1 - 2 18
idx: 1
idxPixel: 7
computedValueForOutput: 135
pixel = 28
shape1 - 2 18
idx: 1
idxPixel: 8
computedValueForOutput: 140
pixel = 29
shape1 - 2 18
idx: 1
idxPixel: 9
computedValueForOutput: 145
pixel = 30
shape1 - 2 18
idx: 1
idxPixel: 10
computedValueF

IndexError: index 18 is out of bounds for axis 1 with size 18

#### Exercise 1.2

Now, we also want to include **padding** of the input. Adjust your implementation of ``cross_correlation()``, such that it pads the input (zero-padding) in a way, that you can center the kernel to each original pixel of the input.

In [ ]:
def cross_correlation_full(input : np.ndarray, kernel : np.ndarray) -> np.ndarray:
  # Your code goes here
  raise NotImplementedError

#### Exercise 1.3
In the lecture, you also learned about convolution. What are the differences between cross-correlation and convolution?

Your answer goes here

#### Exercise 1.4

Provide the implementation of convolution in the following. The implementation should use **same padding** with zeros.

In [ ]:
def convolution2d(input : np.ndarray, kernel : np.ndarray) -> np.ndarray:
  # Your code goes here
  raise NotImplementedError

Now, convolve the flower image with a mean filter. Display both, the input image and the output of the convolution.

What happened? Explain.

Hint: A larger kernel may help to better identify the differences when the images are displayed small.

In [3]:
flowers = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/crush.png?raw=true"),cv2.COLOR_BGR2GRAY)

In [ ]:

# Your code goes here
kernel = ...

Your answer goes here.

#### Exercise 1.5

In a further step, we also want to convolve an RGB image channel wise. In detail, the input is an RGB image with 3 channels and we have a kernel of shape $(n,n)$. The output should have the same shape as the input, therefore, we want to apply zero-padding to the input. Afterwards, display the image.


In [4]:
flowers_rgb = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/crush.png?raw=true"),cv2.COLOR_BGR2RGB)

In [ ]:

def convolution_channelwise(input : np.ndarray, kernel : np.ndarray) -> np.ndarray:
  # Your code goes here
  raise NotImplementedError

#### Exercise 1.6

The following kernel is separable. Find $w_1$ and $w_2$, such that $w = w_1 \times w_2$
$$w = \frac{1}{24}\left[\begin{array}{rrr}
1 & 24 & 3 \\
\frac{4}{3} & 32 & 4 \\
0 & 0 & 0 \\
\end{array}\right]$$

#### Exercise 1.7

Show, that the Gaussian kernel $G(s,t)$ from the lecture is separable.
$$ G(s,t) =  \frac{1}{(2\pi\sigma^2)} * e^-(\frac{x^2 + y^2}{2\sigma^2}) $$

### Exercise 2 - Low-pass Filter

#### Exercise 2.1
- On a higher level: What are low-pass filters and what purpose do they serve?
- How do they work?

Your answer goes here.

#### Exercise 2.2

The image of Crush the turtle got a little bit corrupted and noise was added. We want to fix this by smoothing the image with the help of low-pass filters.

But first, we want to see how noisy the image actually got. For this, we can use the Mean-squared error and compare the original image of crush to the noisy image.

The mean-squared error is defined as:

$MSE = \frac{1}{n}\sum_{i=1}^n (I_i - \hat{I}_i)^2$, where
- $n$ is the total number of pixels
- $I(i)$ and $\hat{I}(i)$ are the intensity values of pixel $i$ in the original and output images.

Implement the mean-squared error for grayscale images AND rgb images.

In [4]:
crush_original = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/crush.png?raw=true"), cv2.COLOR_BGR2GRAY)
crush_noisy = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/crush_noisy.png?raw=true"), cv2.COLOR_BGR2GRAY)


In [ ]:

fig, (ax0, ax1) = plt.subplots(ncols=2, figsize=(16,8))
ax0.imshow(crush_original, cmap="gray", vmin=0, vmax=255)
ax0.set_title("Crush")
ax0.axis("off")
ax1.imshow(crush_noisy, cmap="gray", vmin=0, vmax=255)
ax1.set_title("Crush + Noise")
ax1.axis("off")
fig.tight_layout()

In [ ]:
# Your code goes here
def mse(input1 : np.ndarray, input2 : np.ndarray) -> float:
  raise NotImplementedError

#### Exercise 2.3

A simple approach would be the mean filter. Implement the mean filter, compute the mse of the output and the original image and display your output image. For this, use your implementation from exercise 1.

(In case you were not able to provide a solution for exercise 1.2 or exercise 1.5, you are allowed to use the `convolve2d()` or `correlate2d()` implementation from `scipy`. This also holds for all exercises below that depend of these.)

In [ ]:
# Your code goes here

#### Exercise 2.4

Another possible approach would be the Gaussian kernel. However, we need to define the kernel before.

Implement a Gaussian kernel generator that outputs Gaussian filters. The function takes two inputs as parameters:
- `kernel_size` defines the size of the quadratic, odd-shaped kernel, e.g., $5\times 5$.
- `sigma` depicts the standard deviation of the Gaussian distribution

In [ ]:
# Your code goes here
def gaussian_kernel_generator(kernel_size : int, sigma : float) -> np.ndarray:
  raise NotImplementedError

In order to find a good gaussian kernel, provide 5 different combinations of parameters. By doing so, smooth the image with the respective gaussian kernels and compute the mse between the outputs and the original image. Lastly, display the best result.

In [ ]:
# Your code goes here

Your answer goes here

Use the following cell to display the original image, the output of the mean-filter and the output of the gaussian filter.

In [ ]:
crush_mean = ...
crush_gaussian = ...

fig, (ax0, ax1, ax2, ax3) = plt.pyplot.subplots(ncols=4, figsize=(20,10))
ax0.imshow(crush_original, cmap="gray", vmin=0, vmax=255)
ax0.set_title("Original")
ax0.axis("off")
ax1.imshow(crush_noisy, cmap="gray", vmin=0, vmax=255)
ax1.set_title("Noise")
ax1.axis("off")
ax2.imshow(crush_mean, cmap="gray", vmin=0, vmax=255)
ax2.set_title("Mean Filter")
ax2.axis("off")
ax3.imshow(crush_gaussian, cmap="gray", vmin=0, vmax=255)
ax3.set_title("Gaussian Filter")
ax3.axis("off")
fig.tight_layout()

### Exercise 3 - Sobel Filter

The [Sobel Filter](https://en.wikipedia.org/wiki/Sobel_operator) is a high-pass filter, which can be used for edge detection, but also for image sharpening.

In the following, we first want to use the filter to detect the edges of our RGB butterfly image. Then, we can use the the output in order to sharpen a blurr version of the flower image.

In [ ]:
butterfly = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/butterfly.png?raw=true"),cv2.COLOR_BGR2RGB)
butterfly_blurred = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/butterfly_blurred.png?raw=true"),cv2.COLOR_BGR2RGB)


In [ ]:

plt.imshow(butterfly_blurred, vmin=0, vmax=255)

#### Exercise 3.1
Answer the following questions:
- What are high-pass filters and what are they used for?
- How are they different from low-pass filter?

Your answer goes here

#### Exercise 3.2

Implement the Sobel filter while using the implementations of exercise 1. Apply the filter channel-wise and display your results.

In [ ]:
# Your code goes here

#### Exercise 3.3

Use the detected edges to sharpen the blurred image and display the blurred butterfly image and the sharpened image.

In [ ]:
# Your code goes here

### Exercise 3.4

Another high-pass filter is the Laplacian filter. This filter is also used as a edge detector.

Apply the Laplacian filter to the original butterfly image and display the edges of all three channels separately.

In [ ]:
# Your code goes here

### Exercise 4 - Canny

#### Exercise 4.1

Besides the aforementioned high-pass filters, there are also other types of apporaches, that are used for edge detection. For example, the [Canny edge detector](https://docs.opencv.org/4.x/da/d22/tutorial_py_canny.html). Familiarize yourself with this algorithm and apply it to our flowers image.

Hint: You do not have to implement Canny edge detector on your own, you are allowed to use any library.

In [5]:
flowers = cv2.cvtColor(url2img("https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/flowers.jpg?raw=true"),cv2.COLOR_BGR2GRAY)


In [ ]:

# Your code goes here
flowers_canny = ...


#### Exercise 4.2

Use the Sobel filter again for the flowers image and compare the output to the Canny output.

What differences can you see?
Which detection approach would you prefer in this case and why?

Hint: For this task you can just use the grayscale image.

In [ ]:
# Your code goes here
flowers_sobel = ...

In [ ]:
fig, (ax0, ax1, ax2) = plt.subplots(ncols=3, figsize=(16,4))

ax0.imshow(flowers, cmap="gray", vmin=0, vmax=255)
ax0.set_title("Input image")
ax0.axis("off")
ax1.imshow(flowers_canny, cmap="gray", vmin=0, vmax=255)
ax1.set_title("Canny")
ax1.axis("off")
ax2.imshow(flowers_sobel, cmap="gray", vmin=0, vmax=1)
ax2.set_title("Sobel Filter")
ax2.axis("off")
fig.tight_layout()

Your answer goes here.

## Second Part - Filtering in the Frequency Domain



In [6]:
url = 'https://www.shutterstock.com/image-photo/view-city-koeln-cologne-germany-600nw-107359316.jpg'

In [ ]:
img = url2img(url)
grayscale_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(grayscale_img, cmap='gray')
plt.axis(False)

### Exercise 5 - 2D Discrete Fourier Transform


The 2D DFT is defined as

$$
F(u,v) =\sum_{x=0}^{M-1} \sum_{y=0}^{N-1} f(x,y) e^{-j2\pi(v\frac{y}{N}+u\frac{x}{M} )},
$$

which we can manipulate:

$$
\begin{equation}
\begin{split}
F(u,v)  & = \sum_{x=0}^{M-1} \sum_{y=0}^{N-1} f(x,y) e^{-j2\pi(v\frac{y}{N}+u\frac{x}{M} )} \\
 & = \sum_{x=0}^{M-1} \sum_{y=0}^{N-1} f(x,y) e^{-j2\pi v \frac{y}{N}} e^{-j2\pi u \frac{x}{M}} \\
 & = \sum_{x=0}^{M-1} \left[\sum_{y=0}^{N-1} f(x,y) e^{-j2\pi v \frac{y}{N}} \right] e^{-j2\pi u \frac{x}{M}},
\end{split}
\end{equation}
$$

where the term in square brackets is the 1D DFT of the x-th column of the image.  
 This means that we can replace each column of an image by its 1D DFT, and then compute the row-wise 1D DFT.

- Implement a function to compute the **centred** 2D DFT of a grayscale image given as a numpy matrix.

- Implement the inverse transform.

You can use a library 1D transform, for example `numpy.fft.fft`. **DO NOT** use a library 2D DFT transform for this exercise.

Exemplify your function by visualising the (centred) _spectrum_ and _phase_ of some images.

For a better visualization, remember to use a log transform on the spectra


In [ ]:
# Your code goes here:

# Implement 2D Discrite Fourier Transform and its Inverse

# Plot images and their centred, log-transformed spectra

### Exercise 6 - Spectrum manipulation
The following images have been corrupted by periodic noise. Fix their DFT spectra and show the results. You can use any image editor software (e.g. MS Paint).

Show:
- The DFT spectrum of the corrupted image
- The "fixed" DFT spectrum.
- The restored image.

Hint: remember to take the phase into account when doing the IDFT.

![Corrupted image](https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/corrupted_img.png?raw=true)

![Corrupted image](https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/moon.jpg?raw=true)

In [ ]:
# Your code goes here:

# Plot the spectra of the images above

# Edit the spectra, with your favorite tool, to remove the periodic noise

# Upload the new spectra to the notebook, and visualize it

# Transform the spectra to space domain, and plot the restored images

### Exercise 7 - Filters in Frequency Space
Implement the following filters in the frequency domain:
- Ideal LPF
- Gaussian LPF
- Butterworth LPF
- Ideal HPF
- Gaussian HPF
- Butterworth HPF

The functions should:
- take a grayscale image as input
  - you can extend it to RGB
- convert them to the frequency domain
- compute the filter kernels in the frequency domain
- apply the filter in frequency domain
- compute the inverse transform
- return the inverse transform as a grayscale image.

Visualise the results of applying these filters on some images

In [ ]:
# Your code goes here:

# Implement the above mentioned filters

# Plot one image, and the filters outputs

# example prototype
def apply_gaussian_filter(img, d0):
  # ...
  return

### Exercise 8 - Deconvolution
You are a Remote Sensing Engineer at DLR, and your team has recently launched a new space telescope. Unfortunately, due to undetected mirror faults, the images it acquires are not worth the billion euros of tax-payer money that were spent on it.  

![galaxy shot](https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/telescope_broken.png?raw=true)

Luckily, since you've taken Prof. Bozek's course, you can spare the costs of a repair mission by fixing the images here in Earth.

This is a shot of a distant lone star taken by the telescope. Being such a small object, a working shot of the star should look like a single impulse, and is a good approximation of the [Point Spread Function](https://en.wikipedia.org/wiki/Point_spread_function) of the damaged telescope.


In [7]:
url = 'https://github.com/bozeklab/ComputerVision_SS24/blob/main/resources/assignment_2/star_broken_16bits.png?raw=true'

In [ ]:
img = url2img(url)/ 65535 # this image has 16 bits of depth

plt.imshow(img, cmap='gray')
plt.axis(False)

Use the star shot to fix the galaxy image, and display it. **Implement** the naive deconvolution code. Feel fry to try more advanced deconvolution algorithms.

In [ ]:
# Your code goes here

# Implement naive deconvolution

# Restore the galaxy image using deconvolution

# Show the restored image